    - name: install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: start nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: deploy website
      copy:
        src: website/
        dest: /var/www/html/
        owner: root
        group: root
        mode: '0755'

    - name: install certbot 
      apt: 
        name:
          - certbot
          - python3-certbot-nginx 
        state: present 

    - name: generate ssl certificate 
      command: >
        certbot --nginx 
        -d winn.top
        --non-interactive
        --agree-tos
        -m admin@winn.top
      args:
        creates: /etc/letsencrypt/live/winn.top/fullchain.pem
         

    - name: certbot auto renew
      cron: 
        name: certbot renew
        job: certbot renew --quiet 
        minute: "0"
        hour: "3"

