name: Deploy Website 
  
on: 
  push:
    branches:
      - main 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ansible
        run: | 
          apt update
          apt install ansible -y 

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 159.75.156.10 >> ~/.ssh/known_hosts



      - name: Run Ansible
        run: | 
          ansible-playbook -i ansible/inventory.yml ansible/Nginx.yml
